export const SET_BANNERS ='set_banners'
export const SET_FULLSCREEN = 'set_fullscreen'
export const SET_CURRENTINDEX = 'set_currentIndex'
export const SET_PLAYLIST = 'set_playlist'
export const GET_PRIVATEFM = 'get_privateFm'
